### ISSUE TITLE
No class "Insurance" in source code

### ISSUE THREAD

**Issue by anbinhtrong** [EasyPost/easypost-csharp#84] opened 2017-04-24 02:49 UTC
I write an example in the page: https://www.easypost.com/docs/api/csharp.html#insurance
When I compile, I have an error: "The name 'Insurance' does not exist in the current context"
I look up in github, I can't find class Insurance.cs.
Do you miss the file?

**Comment by att14** [comment] 2017-04-24 19:34
This is a duplicate of #47. Can you write into support@easypost.com for more information?

**Closed by att14** 2017-04-24 19:34 UTC
