### ISSUE TITLE
Nullreference Exception when creating a shipment

### ISSUE THREAD

**Issue by TGKN** [EasyPost/easypost-csharp#150] opened 2020-08-21 06:32 UTC
Hi,
I keep getting Nullreference exceptions when creating a shipment (About 10 per day and not specifically reproduceable). Here's the error and stack trace:
Object reference not set to an instance of an object.

System.NullReferenceException: Object reference not set to an instance of an object. at EasyPost.Resource.Merge(Object source) at EasyPost.Shipment.Create() 

Any ideas what could be causing this randomly appearing issue?
Kai

**Comment by LoganSimonsen** [comment] 2021-07-21 15:16
this might be fixed by upgrading Rest Sharp to 105.0.0 or later?

https://github.com/restsharp/RestSharp/blob/dev/releasenotes.md

**Comment by Justintime50** [comment] 2021-07-21 19:30
@LoganSimonsen interesting find!

@TGKN what version of this client library and/or RestSharp are you using?

**Comment by TGKN** [comment] 2021-08-03 07:11
Hi,
I am using the tip revision of the easypost client library (not the nuget package) and the RestSharp version I am using is 106.11.4

**Comment by Justintime50** [comment] 2021-08-12 17:16
Could you provide a snippet/gist/link to the code you are using and the data you are passing so we can look into this further?

**Comment by TGKN** [comment] 2021-08-16 15:18
Hi,
I don't think it is related to my code  - and also not to the data that is being passed. There seems to be an issue in the EasyPost.Resource.Merge(Object source) method, I keep getting these kind of errors when creating shipments or creating new addresses. I was witnessing the error once myself trying to create a shipment. I tried again just a couple of seconds later sending the same data and it worked fine. Is it possible that the easypost server sends a response that cannot be dealt with on the client side?

**Comment by overforkover77** [comment] 2022-02-26 18:51
@Justintime50 , I have been experiencing the same issue/scenario that @TGKN has.  

Experiencing this with single call purchasing of  'Orders' using our 'test' key.

Using the same order(s) data for our testing/implementation work, we see this randomly occur.  Other times, with same exact data, it does not.

**Exception info:**

> System.NullReferenceException
>   HResult=0x80004003
>   Message=Object reference not set to an instance of an object.
>   Source=mscorlib
>   StackTrace:
>    at System.Object.GetType()
>    at EasyPost.Resource.Merge(Object source)

I inspected the response using Fiddler to see if the raw HTTP response would show any helpful information.  It seems the 'Gateway Timeout' response does not contain the 'errors' property.  

Could this be the root of the issue we are seeing?



**Gateway Timeout JSON response:**
Results in the NullReferenceException.
Lacking the 'errors' property.
```
{
    "error": {
        "message": "A connection to our internal servers could not be established. Please retry in a few minutes. Ongoing incidents are recorded at http://www.easypoststatus.com/; please contact support@easypost.com if this error persists and there is no status update posted.",
        "code": "Gateway Timeout"
    }
}
```

**Carrier Timeout JSON response:**
This response is properly returned from the API/library.
```
{
    "error": {
        "code": "SHIPMENT.POSTAGE.TIMED_OUT",
        "message": "Unable to complete shipment purchase: carrier timed out responding to our request. Please try again or contact support",
        "errors": []
    }
}
```

**Comment by Justintime50** [comment] 2022-02-28 21:01
@overforkover77 thanks for the additional details! We are currently looking into this issue and will report back here shortly. We have a few in-flight PRs that may address this issue.

**Comment by nwithan8** [comment] 2022-03-08 22:12
> @Justintime50 , I have been experiencing the same issue/scenario that @TGKN has.
> 
> Experiencing this with single call purchasing of 'Orders' using our 'test' key.
> 
> Using the same order(s) data for our testing/implementation work, we see this randomly occur. Other times, with same exact data, it does not.
> 
> **Exception info:**
> 
> > System.NullReferenceException
> > HResult=0x80004003
> > Message=Object reference not set to an instance of an object.
> > Source=mscorlib
> > StackTrace:
> > at System.Object.GetType()
> > at EasyPost.Resource.Merge(Object source)
> 
> I inspected the response using Fiddler to see if the raw HTTP response would show any helpful information. It seems the 'Gateway Timeout' response does not contain the 'errors' property.
> 
> Could this be the root of the issue we are seeing? [Simple gist attempting to validate assumption](https://gist.github.com/overforkover77/2787e8a0c11f78f97981757db530d7d0) (Using NetFramework bits, I believe.)
> 
> **Gateway Timeout JSON response:** Results in the NullReferenceException. Lacking the 'errors' property.
> 
> ```
> {
>     "error": {
>         "message": "A connection to our internal servers could not be established. Please retry in a few minutes. Ongoing incidents are recorded at http://www.easypoststatus.com/; please contact support@easypost.com if this error persists and there is no status update posted.",
>         "code": "Gateway Timeout"
>     }
> }
> ```
> 
> **Carrier Timeout JSON response:** This response is properly returned from the API/library.
> 
> ```
> {
>     "error": {
>         "code": "SHIPMENT.POSTAGE.TIMED_OUT",
>         "message": "Unable to complete shipment purchase: carrier timed out responding to our request. Please try again or contact support",
>         "errors": []
>     }
> }
> ```

I'm looking into this now. Just to clarify, that Gateway Timeout error was thrown as part of the `NullReferenceException`? I ask because the `NullReferenceException` was thrown by the `Merge()` function, which is supposed to take the response data-deserialized-object and merge it with the existing local object. If the API returned an error, an incorrect object could be accidentally passed into that `Merge` function, but our system is supposed to throw an exception before that point.

**Comment by overforkover77** [comment] 2022-03-11 13:18
> Just to clarify, that Gateway Timeout error was thrown as part of the NullReferenceException?

I had noticed that when we experienced the `NullReferenceException` the response from the API was always the 'Gateway Timeout'.  

> What version of the library are you using that produces the NullReferenceException?

@nwithan8 I believe we were using 2.8.1 at the time.  We are now on 2.8.2.

I have not seen the issue since posting this issue, however we have since moved from 'test' to 'production', so that may be a factor as well.

**Comment by nwithan8** [comment] 2022-03-11 15:07
@overforkover77 Thank you for that information. We are continuing to triage this.

**Comment by nwithan8** [comment] 2022-04-15 19:32
@overforkover77 v3.0.0 is now out with a lot of changes. I was unable to reproduce this error in v3.0.0. Could you please verify if you are still experiencing this this issue in the latest version? Closing for now.

**Closed by nwithan8** 2022-04-15 19:32 UTC
Labels: triage, cant reproduce
